export const boats = [
  { id: 'patrol-boat', name: 'Harbour Watch 12', phase: 'Basic Recognition', emoji: '🚤', silhouette: 'Low hull, blue light, antenna cluster.', visualCue: 'A compact vessel darts along the harbour wall with exactly one official-looking clipboard onboard.', correct: 'Patrol boat', options: ['Patrol boat', 'Fishing boat', 'Ferry', 'Tugboat'], feedback: 'Correct. A tidy patrol boat with a regulation amount of authority.' },
  { id: 'ferry', name: 'MV Public Consultation', phase: 'Basic Recognition', emoji: '⛴️', silhouette: 'Boxy profile, passenger windows, ramp doors.', visualCue: 'It is large, rectangular, full of commuters, and pretending not to hear your radio call.', correct: 'Ferry', options: ['Cargo ship', 'Ferry', 'Research vessel', 'Minehunter'], feedback: 'Correct. Sometimes a ferry is permitted to simply be a ferry.' },
  { id: 'submarine', name: 'HMAS Introvert', phase: 'Basic Recognition', emoji: '🛳️', silhouette: 'Dark cigar hull, tiny sail, no social availability.', visualCue: 'A sleek dark shape surfaces briefly, sees the meeting invite, and begins diving again.', correct: 'Submarine', options: ['Whale', 'Submarine', 'Cargo ship', 'Absence of boat'], feedback: 'Correct. It has declined stakeholder engagement but remains a submarine.' },
  { id: 'research-trawler', name: 'RV Grant Extension', phase: 'Operational Ambiguity', emoji: '🚢', silhouette: 'Trawler hull, sensor mast, too many graduate students.', visualCue: 'Nets, sensors, and a hand-painted sign reading “science, probably” sway in the spray.', correct: 'Research trawler', options: ['Fishing boat', 'Research trawler', 'Customs launch', 'Offshore support vessel'], feedback: 'Correct. The fish are incidental; the spreadsheet is the payload.' },
  { id: 'support-vessel', name: 'OSV Mild Obligation', phase: 'Operational Ambiguity', emoji: '🚢', silhouette: 'Broad working deck, crane, stack of mystery containers.', visualCue: 'It has a crane, a helipad outline, and the energy of a subcontractor invoice.', correct: 'Offshore support vessel', options: ['Offshore support vessel', 'Ferry', 'Sailboat', 'Ceremonial tugboat'], feedback: 'Correct. It supports something offshore, and no one has asked too many follow-up questions.' },
  { id: 'legacy-hull', name: 'Former HMAS Still Useful', phase: 'Bureaucratic Escalation', emoji: '🛥️', silhouette: 'Old grey hull, new banner, suspicious optimism.', visualCue: 'A decommissioned hull passes with a ribbon-cutting podium welded to the aft deck.', correct: 'Legacy patrol asset', options: ['Legacy patrol asset', 'Luxury yacht', 'Fishing boat', 'Unknown'], feedback: 'Correct. It stopped being old when the briefing called it legacy.' },
  { id: 'strategic-inflatable', name: 'Rigid Inflatable Future Option', phase: 'Bureaucratic Escalation', emoji: '🛶', silhouette: 'Inflatable tubes, absurd radar mast, contractor decal.', visualCue: 'A small inflatable carries a radar mast bigger than its future sustainment plan.', correct: 'Capability-adjacent maritime platform', options: ['Dinghy', 'Capability-adjacent maritime platform', 'Special forces craft', 'Procurement incident'], feedback: 'Bureaucratically correct. While visually a dinghy, it has been funded as a platform.', memo: 'Memo: anything with a mast and a contractor logo is no longer “small.”' },
  { id: 'kayak-trenchcoat', name: 'Composite Paddled Formation', phase: 'The Sea Becomes Impossible', emoji: '🛶', silhouette: 'Tall canvas column, six paddles, poor balance.', visualCue: 'Three kayaks wobble under a trench coat and insist they are one sovereign vessel.', correct: 'Composite low-signature paddled formation', options: ['Composite low-signature paddled formation', 'Smuggling craft', 'Performance art', 'Unknown vessel'], feedback: 'Correct. Unfortunately, the formation is recognised under the kayaking capability review.' },
  { id: 'budget-carrier', name: 'HMAS Fiscal Restraint', phase: 'The Sea Becomes Impossible', emoji: '🛳️', silhouette: 'Flat deck, one drone, many savings claims.', visualCue: 'A flat-decked barge launches a toy drone while a banner promises sovereign capability.', correct: 'Budget-neutral aircraft carrier', options: ['Budget-neutral aircraft carrier', 'Barge', 'Ferry', 'Drone picnic platform'], feedback: 'Correct. The aircraft is small, but the ambition is full displacement.' },
  { id: 'floating-kpi', name: 'Q4 Maritime Deliverable', phase: 'The Sea Becomes Impossible', emoji: '📈', silhouette: 'No hull, just a chart floating confidently.', visualCue: 'A laminated dashboard drifts past, buoyed by optimism and red-amber-green status icons.', correct: 'Unidentified floating KPI', options: ['Unidentified floating KPI', 'Mine', 'Weather balloon', 'Audit mode objective'], feedback: 'Correct. It has no propulsion, but it is moving the program forward.' }
];

export const memos = [
  'All vessels with banners are community engagement assets until further notice.',
  'Please avoid “unknown.” Preferred wording is “classification opportunity.”',
  'Tugboats may now be strategic enablers if photographed from a low angle.',
  'Anything observed near a minister is operationally significant by default.'
];
